Requests DEFINITIONS ::= BEGIN

    Connected ::= SEQUENCE{
        message     UTF8String,
        number      INTEGER,
        connected   BOOLEAN
    }

    Request ::= SEQUENCE{
        column     INTEGER,
        row        INTEGER
    }

    Response ::= SEQUENCE{
        column     INTEGER,
        row        INTEGER,
        hit        BOOLEAN,
        sunk       BOOLEAN
    }

    Ready ::= SEQUENCE{
        ready      BOOLEAN
    }

END